-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 17:26:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Fbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Fbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Fbook` DEFAULT CHARACTER SET utf8 ;
USE `Fbook` ;

-- -----------------------------------------------------
-- Table `Fbook`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fbook`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fbook`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fbook`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `amount` INT NULL,
  `borrower` INT NULL,
  `bookName` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `brief` TEXT NULL,
  `user_id` INT NOT NULL,
  `times` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_book_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Fbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fbook`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fbook`.`record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_record_user1_idx` (`user_id` ASC),
  INDEX `fk_record_book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Fbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `Fbook`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
